language: node_js
node_js:
  - "6.9.2"
script:
  - "npm run test"
after_success:
  - "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
notifications:
  email: false
  slack:
    secure: "GJbKzQOmF1EGJ5pLRfxoZAI+xUWix/1FpEfyzbQ/hpjlJJl2nP6nvaVzvu5ARqOKi3CBFVJCwaXFsZ8z0a5qezYuJzcCZQ7XYd6YtOafBjUXmcEHpB2PadnCJ7WZPzhRbZLixHk2edmyoi16rmt/70upf2LtxBWIsCt6OddGisaHMSRg/UU3RCo1Farssj1Wz4qzEFQgDf6B6CyCg1ZaqpYH0xRyi+aBTwAtr9lOsx2HH3L70V3r3Zt1rnDm1g39wKrNSLEwUducinlfP5tIJk4/Spm1cpO58uv6JAkFGT5EW9bc8m50E/tRHfKYQ7p4/5BmBdxZaCQET7awj9gLzFRLkMthMXbmJLKDL/ODkK42SzKv2c+KtBWnzT6FEV3gdpYaPZLqQ7lboFiMD+s6yaQRbepciu4CtbgZNUn13zmKMmHjs+CWzKRyqXLsd1mQDRgI4FSoWUHoWCmAf5XRxxXOBK5X9KgJTg10vGZXQqU5ZRPXS/X+ZvAxQITCgCTE3LH4Nd7SRgpXkJM0Joxgdwbg/6ygGKbraS9GChcCzvHBNAzjGBrX/SRACYLRdok3FWJiyoV1En8z233DUWVW/D3vTPK84DMK8mMG6YgDVegX+ifvFj5cCKqCaB6EX9t1b4EB3We9IAm+mdmKJTGFpEvW8KEVQDmvs2Qn+i1qCRI="
