# Provider Configs.
providers:
    twitch:
        base: 'https://twitch.tv/'
        api: 'https://api.twitch.tv/'
        clientId: ''
    glimesh:
        base: 'https://glimesh.tv/'
        api: 'https://glimesh.tv/api'
        clientId: ''
# API Configs.
api:
    exozone:
        base: 'https://api.exozone.net/'
    lastfm:
        base: 'https://ws.audioscrobbler.com/2.0/'
        key: ''
    weather:
        base: 'http://api.openweathermap.org/data/2.5/weather'
        key: ''
    pretzel:
        base: 'https://www.pretzel.rocks/api/v1/'
