# Provider Configs.
providers:
    mixer:
        base: 'https://mixer.com/'
        api: 'https://mixer.com/api/v1/'
        clientId: ''
    twitch:
        base: 'https://twitch.tv/'
        api: 'https://api.twitch.tv/'
        clientId: ''
    smashcast:
        base: 'https://www.smashcast.tv/'
        api: 'https://api.smashcast.tv/'

# API Configs.
api:
    exozone:
        base: 'https://api.exozone.net/'
    lastfm:
        base: 'https://ws.audioscrobbler.com/2.0/'
        key: ''
    weather:
        base: 'http://api.openweathermap.org/data/2.5/weather'
        key: ''
    pretzel:
        base: 'https://www.pretzel.rocks/api/v1/'
